### ISSUE TITLE
Add support for speaker groups

### ISSUE THREAD

**Issue by Alibozis** [stefan-schweiger/dev.schweiger.echo#3]
Hi :) 
Would it be possible to make it so groups can be imported into homey, så one device could control all my alexa's?
I have a group called everwhere and it would be perfect to get that in homey.

Thanks for your work.

Allan

**Comment by stefan-schweiger** [comment]
I just tried to look into it very quickly and it seems like you won't be able to do things like "Say <message>" or "Tell <command>" for a speaker group. But just getting volume control and play/pause should be possible with a bit of polishing.

**Comment by Alibozis** [comment]
That would be super nice, and enough :) So really great if you would do it.

**Comment by stefan-schweiger** [comment]
Just pushed a test version which includes groups

**Comment by Alibozis** [comment]
Seems like it works as expected :) Is it possible to get pictureart and name of the track playing???
Would be great when using it on dashboard.

**Comment by stefan-schweiger** [comment]
Should actually already be supported. If you can see it when you are playing on a single speaker it should also work for a group. But maybe not every media source provides it.
